//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4_Datos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimGeography
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimGeography()
        {
            this.DimCustomer = new HashSet<DimCustomer>();
            this.DimSalesTerritory = new HashSet<DimSalesTerritory>();
            this.DimStore = new HashSet<DimStore>();
        }
    
        public int GeographyKey { get; set; }
        public int GeographyTypeKey { get; set; }
        public string GeographyType { get; set; }
        public string ContinentName { get; set; }
        public string CityName { get; set; }
        public string StateProvinceName { get; set; }
        public string RegionCountryName { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Geometry { get; set; }
        public Nullable<int> ETLLoadID { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimCustomer> DimCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimSalesTerritory> DimSalesTerritory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimStore> DimStore { get; set; }
    }
}
