//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4_Datos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimStore()
        {
            this.DimMachine = new HashSet<DimMachine>();
            this.FactInventory = new HashSet<FactInventory>();
            this.FactITSLA = new HashSet<FactITSLA>();
            this.FactSales = new HashSet<FactSales>();
            this.FactSalesQuota = new HashSet<FactSalesQuota>();
        }
    
        public int StoreKey { get; set; }
        public int GeographyKey { get; set; }
        public Nullable<int> StoreManager { get; set; }
        public string StoreType { get; set; }
        public string StoreName { get; set; }
        public string StoreDescription { get; set; }
        public string Status { get; set; }
        public System.DateTime OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<int> EntityKey { get; set; }
        public string ZipCode { get; set; }
        public string ZipCodeExtension { get; set; }
        public string StorePhone { get; set; }
        public string StoreFax { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string CloseReason { get; set; }
        public Nullable<int> EmployeeCount { get; set; }
        public Nullable<double> SellingAreaSize { get; set; }
        public Nullable<System.DateTime> LastRemodelDate { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Geometry { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> ETLLoadID { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual DimGeography DimGeography { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimMachine> DimMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactInventory> FactInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactITSLA> FactITSLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactSales> FactSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactSalesQuota> FactSalesQuota { get; set; }
    }
}
