//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4_Datos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactOnlineSales
    {
        public int OnlineSalesKey { get; set; }
        public System.DateTime DateKey { get; set; }
        public int StoreKey { get; set; }
        public int ProductKey { get; set; }
        public int PromotionKey { get; set; }
        public int CurrencyKey { get; set; }
        public int CustomerKey { get; set; }
        public Nullable<int> SalesOrderLineNumber { get; set; }
        public int SalesQuantity { get; set; }
        public decimal SalesAmount { get; set; }
        public int ReturnQuantity { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public Nullable<int> DiscountQuantity { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public decimal TotalCost { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> ETLLoadID { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string SalesOrderNumber { get; set; }
    }
}
